# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myveggarden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenset',
            name='cycle_time_set',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='gardenset',
            name='recirculation_pump_set',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AddField(
            model_name='gardenset',
            name='solution_pump_set',
            field=models.CharField(default='', max_length=140),
        ),
    ]
