# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-06-26 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myveggarden', '0004_auto_20180623_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gardenset',
            name='next_cycle_set',
        ),
    ]
