# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbracoProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(default='+00 00 0000 0000', max_length=20)),
                ('department', models.CharField(default='', max_length=50)),
                ('jobTitle', models.CharField(default='', max_length=50)),
                ('is_administrator', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierCode', models.IntegerField(default=0)),
                ('address', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default='', max_length=15)),
                ('contactPerson', models.CharField(default='', max_length=50)),
                ('phoneNumber', models.CharField(default='+00 00 0000 0000', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
